assets/_scss/_common_margin-vertical.scss
readme.txt

おそらく見出しの下の余白について、spacing から レディング分引いた値に指定してあったが、
見出しの文字サイズが大きかったりする事から結局その方が余白が大きくなりすぎたりするため削除

[ デザイン仕様変更 ] 見出しの下の余白指定削除

---

assets/_scss/_navigation_additional-class.scss
readme.txt

https://github.com/vektor-inc/x-t9/issues/27
ナビゲーションブロックの子階層メニューのページを表示している時、親メニューへのスタイルを追加しました。

【確認待ち】[ ナビゲーションブロック ] 子階層メニューのページを表示している時、親メニューへのスタイリングを追加

---

readme.txt
theme.json

https://make.wordpress.org/core/2023/10/17/miscellaneous-editor-changes-in-wordpress-6-4/
WordPress 6.4 環境でグループブロックに背景画像指定ができるように
* WordPress 6.4 の環境でグループブロックを配置して背景画像設定UIが出ている事を確認
* もし気が向いたら https://make.wordpress.org/core/2023/10/17/miscellaneous-editor-changes-in-wordpress-6-4/ を読んで指定方法に問題がないか確認

【2人目確認待ち】Added support for the background image feature in Group blocks, introduced in WordPress 6.4.

---

assets/_scss/_header.scss
readme.txt
theme.json

まぁ デザイン指定はできるだけ theme.json からにした方が良い...
サイトタイトルタグへのデザイン指定をCSSファイルからtheme.jsonに移行
-> CSS変更なので無し
* npm run build
* サイトタイトルの文字が太字になっている & hover で下線がつくかどうか
---
* プルしたか？
* ビルドしたか？

【確認中】サイトタイトルタグへのデザイン指定をCSSファイルからtheme.jsonに移行

---

assets/_scss/_block_styles.scss
readme.txt

個別投稿で使っているカラムブロックのgap設定が効かない現象に対応しました。
1. [サイトエディター] > [テンプレート] > [個別投稿] に移動
2. 使われているメインカラムとサイドバーのカラムで使用しているカラムブロックのgapに数値を入れて更新する
(今回はわかりやすく**0**にしています。)
3. フロントエンドで見ると変更前はgapを0にしているはずが余白が開いている状態になります。
この状態から今回のプルリクで2で入力した数値に対応できるようにしました。
1. [サイトエディター] > [テンプレート] > [個別投稿] に移動します。
2. 使われているメインカラムとサイドバーのカラムで使用しているカラムブロックのgapに数値を入れて更新します。
3. フロントエンドで2で入力した数値がカラムブロックに反映されているか確認してください。
---
* プルしたか？
* ビルドしたか？

【フロントエンドのみ】個別投稿で使っているカラムブロックのgap設定が効かない現象に対応

---

readme.txt
theme.json

https://github.com/WordPress/ぐーてんべるぐ/pull/54415
6.5 で CSS level 4 の単位が使えるようになったのでそれに対応
■ Before
■ After
→ 6.5に対応してパラメーターを増やしただけなので省略
* 選択できる単位が上記のように増えている事を確認
* 実装者に同じ
---
* プルしたか？
* ビルドしたか？

Allow using CSS level 4 viewport-relative units

---

assets/_scss/_block_width_editor.scss
readme.txt

https://github.com/vektor-inc/x-t9/issues/248
編集画面用のCSSで`.is-layout-constrained`に`margin-left`、`right`に`auto`がつきますが、`.vk_gridcolcard_item_body` では `display: grid;`になっているため、中に`.is-layout-constrained`があると、`margin-left`と`right`の`auto`が効いて、配置が中央によってしまうため、`.vk_gridcolcard_item_body` の中の`.is-layout-constrained`の`margin`は`unset`で打ち消しました。
1. VK グリッドカラムカードを配置します。
2. VK グリッドカラムアイテム内に段落テキストで適当に文字を打ちます。グループブロックでラップします。グループブロックでラップしても中央によらないことを確認しました。
1. VK グリッドカラムカードを配置します。
2. VK グリッドカラムアイテム内に段落テキストで適当に文字を打ちます。グループブロックでラップします。グループブロックでラップしても中央によらないことを確認してください。
---
* プルしたか？
* ビルドしたか？

【確認中】fix:VK グリッドカラムカードは display: grid;で .is-layout-constrained の要素がmargin:auto;だと中央に寄ってしまうので打ち消し

---

assets/_scss/_variables.scss

https://github.com/vektor-inc/x-t9/issues/260
VK パターンライブラリでLightningテーマのパターンからX-T9にコピペした時に、.has-vk-color-primary-border-colorのクラス名のカラーがX-T9には指定されていないので、VK パターンライブラリを利用する人用に追加しました。
**※ VK パターンライブラリを利用している人にしか関係ないようなクラス名ですので、readmeに書いていませんが、必要でしたら書きます。**
[このパターン](https://patterns.vektor-inc.co.jp/vk-patterns/cram-school_voice-2/)をX-T9テーマに貼り付けて、「保護者の声」部分の横並びブロックのボーダーの色が、X-T9のプライマリーカラーになっていることを確認しました。
[このパターン](https://patterns.vektor-inc.co.jp/vk-patterns/cram-school_voice-2/)をX-T9テーマに貼り付けて、「保護者の声」部分の横並びブロックのボーダーの色が、X-T9のプライマリーカラーになっていることを確認してください。
---
* プルしたか？
* ビルドしたか？

【確認待ち】クラス名 has-vk-color-primary-border-color のカラーを追加

---

assets/_scss/_navigation.scss
readme.txt

https://github.com/vektor-inc/x-t9/issues/265
`.wp-block-navigation__submenu-container`に`.has-background`のクラス名がある場合にpaddingをunsetしました。
cssの微修正なので1人確認でよさそうです。
cssの微修正のみです
cssの微修正のみですのでテストは書いていません
ナビゲーションブロックでサブメニューをもつメニューを設置して、ブロックの設定の［サブメニューとオーバーレイ背景］から背景色を設定します。
フロント画面でサブメニューにpaddingがついていないことを確認しました。
**▼修正前：paddingが付いている状態**
**▼修正後：paddingが付いていない状態**
ナビゲーションブロックでサブメニューをもつメニューを設置して、ブロックの設定の［サブメニューとオーバーレイ背景］から背景色を設定します。
フロント画面でサブメニューにpaddingがついていないことを確認してください。
---
* プルしたか？
* ビルドしたか？

【確認待ち】［css微修正］submenuの背景に色を指定すると has-background で余白がついてしまうので打ち消し

---

assets/_scss/_common_margin-vertical.scss
readme.txt

pタグの下に余白があると、その下にスペーサーを配置した時に、スペーサーに加算した余白がつくため、余白の大きさがサイト全体で安定しないため、毎回手動でスペース前のpタグに margin-bottom:0; 指定をする必要がある。
その事を知らない一般ユーザーがそのまま使うと、余白が安定してない「なんかどこか素人っぽい」サイトになってしまう。
※ もともとこの余白はつかないように作ってあったつもりだったが、おそらく margin-bottom 指定だった（margin-topと総裁される）のが margin-block-end になって加算されるようになったとか...？
pタグ下部の余白を削除
■ Before
■ After
* pタグ上部にはついているので、従来の文章の見た目が崩れる事は少ない
* もともとグループブロック内などの最後の要素の場合は下部の余白は0に指定してあった
以上の事から多少の影響は出るかもしれないが、今後を踏まえると今のうちに削除した方が良いと判断
---
* プルしたか？
* ビルドしたか？

pタグから下部余白削除 / Remove the bottom margin from the p tag.

---

assets/_scss/_common_margin-vertical.scss
readme.txt

https://github.com/vektor-inc/x-t9/pull/270 で p タグ下部から余白を削除したがさすがに影響が大きかった
p タグの次の要素がスペーサーだった場合に余白がなくなるように変更
■ Before
■ After
---
* プルしたか？
* ビルドしたか？

p タグの次の要素がスペーサーだった場合だけ下部余白がなくなるように変更

---

assets/_scss/_button.scss
assets/_scss/_pagenation.scss
readme.txt

WordPress 6.6
■ Before
■ After

[ Other ][ 6.6 ] Fix readmore and pagenation button text color

---

assets/_scss/_button.scss
readme.txt

https://github.com/vektor-inc/x-t9/issues/281
6.6で 編集画面にてボタンのスタイルの輪郭(is-style-outline)の時に背景色がついてしまうので、cssを修正しました。
cssの修正のみ
固定ページなどにコアのボタンブロックを配置して、ボタンのスタイルを「輪郭」(outline)にし、背景色が透明になっていることを編集画面で確認しました。念の為フロント画面も背景が透明になっていることを確認しました。
固定ページなどにコアのボタンブロックを配置して、ボタンのスタイルを「輪郭」(outline)にし、背景色が透明になっていることを編集画面で確認しました。念の為フロント画面も背景が透明になっていることを確認しました。
---
* プルしたか？
* ビルドしたか？

【2人目確認中】［6.6-RC2］［css微修正］編集画面にてコアのボタンブロックのスタイル輪郭で背景色が入ってしまうのを修正

---

assets/_scss/_block_width_editor-wp65.scss
assets/_scss/_block_width_editor.scss
assets/_scss/editor-wp65.scss
assets/_scss/plugin-override/_vk-blocks-override-width.scss
functions.php
readme.txt
theme.json

* 6.5 と 6.6 で編集画面用のCSSを分離
* 6.6 対応幅処理 
■ Before
■ After

Accommodate width adjustment on WordPress 6.6 edit screen

---

assets/_scss/_block_width_editor.scss
readme.txt

Fixed the width of the post title on the edit screen

---

assets/_scss/_variables_wp660.scss
assets/_scss/style.scss
readme.txt
style.css

1. 新規固定ページを作成（タイトル入力のみ / 本文は未入力）
2. 公開画面で記事タイトルの文字が正常なのを確認
3. コードビューで以下のコードを入力して保存
```
<div class="wp-block-buttons">
<div class="wp-block-button"><a class="wp-block-button__link has-primary-background-color has-background wp-element-button">Fill Button</a></div>
<div class="wp-block-button is-style-outline"><a class="wp-block-button__link has-primary-color has-text-color wp-element-button">Outline Button</a></div>
</div>
```
4. 公開画面を見ると記事タイトルの文字サイズが 42px になる
5. このブランチに切り替えて npm run build
6. 公開画面を確認 -> 文字サイズが巨大になりすぎてない事を確認

[ Design Bug Fix ] First aid for an issue where the value of --wp--preset--font-size--huge defined in theme.json is being overwritten by WordPress

---

assets/_scss/_navigation.scss
readme.txt

https://github.com/vektor-inc/vk-patterns/issues/371#issuecomment-2467049040 の
> ### X-T9のキーカラー
>  VKパターンライブラリのパターンで、ナビゲーションの「サブメニューとオーバーレイ背景」をキーカラー、「サブメニューとオーバーレイテキスト」を白にした場合、X-T9テーマではul タグにhas-vk-color-primary-background-color が付与されるが、背景が負けて白になり、テキストは白なので見えない。
> ブロックの設定から設定し直すと問題なく色がつくので問題ないといえば問題ないけど、キーカラーが付くと白背景になるよりは良いかもしれない
▼こちらから症状が確認できます　メニューのサブメニューを展開してください。ナビゲーションの
[ ヘッダー_ミニマムな角丸](https://patterns.vektor-inc.co.jp/vk-patterns/11534/?view=x-t9)
[ ヘッダー_流れるバナー](https://patterns.vektor-inc.co.jp/vk-patterns/11542/?view=x-t9)
VK パターンライブラリのヘッダーのパターンで、「サブメニューとオーバーレイ背景」をキーカラー、「サブメニューとオーバーレイテキスト」を白にした場合、X-T9テーマで貼り直した時に「キーカラー」の設定がLightningとは違うためナビゲーションの設定からクリアされてコア側の白背景色がついてしまうため、（ナビゲーションブロックの「サブメニューとオーバーレイ背景」から設定し直せば問題ないのですが、パターンライブラリのiframe内で白くなるのが気になるため）cssを追加しまし …

[navigation]コア CSS をオーバーライドするように調整しました(VK Pattern Library 用)

---

assets/_scss/_block_width.scss
readme.txt

https://github.com/vektor-inc/vk-patterns/issues/371#issuecomment-2492995960
全幅のグループブロック内に通常幅のグループブロックを入れた場合(コンテナ内に収めるためのクラス名 `is-layout-constrained`がつく )に左側に寄ってしまうため、`margin`の左右に`auto`を追加しました
* テーマをX-T9にして、以下のフッターのパターンを、エディタ > パターン > フッター のところに貼り付ける。
（確認するだけなので、2個一気に貼り付けていただいてoKです）
[フッター 白背景センター配置](https://patterns.vektor-inc.co.jp/vk-patterns/footer-center-bg-white/)
[フッター アイコン背景](https://patterns.vektor-inc.co.jp/vk-patterns/11576/)
* `master` のブランチで、フロント画面で左に寄っていることを確認して、このブランチに切り替え、`npm run build` をして、中央によっていることを確認しました。
実装者と同じ確認方法でお願いします
---
* プルしたか？
* ビルドしたか？

全幅の中のis-layout-constrainedが中央寄せになるように

---

assets/_scss/editor-wp65.scss
assets/_scss/editor.scss

https://github.com/vektor-inc/x-t9/pull/245
編集画面でナビゲーションブロックの間隔指定が効かない
編集画面でナビゲーションブロックに対して gap:0; 指定がしてあった。
おそらく旧バージョンのWordPressでは共有のgapが自動的についてしまっていたために、それを打ち消す目的で追加したものと思われる。
しかしながら、現行バージョンでは左右の gap は0指定がなくてもつかなくなり、不要となったため削除

[ navigation ][ fix ] 編集画面でのナビゲーションのGap指定削除

---

assets/_scss/_navigation.scss
assets/_scss/_navigation_additional-class.scss
readme.txt

ナビゲーションのオーバーレイをオフにするとスタイルがいくつか適用されなくなる不具合を修正
ナビゲーションのオーバーレイをオフに指定すると...
* サブメニューアイテムの余白があたらなくなる
* メインメニューアイテムのサブメニューアイコンの右側の余白があたらなくなる
* アクティブボーターボドムのスタイルが当たらなくなる
★ ナビゲーションオーバーレイをオフにする事によって dom / クラス名 が変動する事を想定されていなかった
■ Before
もとが .wp-block-navigation__responsive-container に対してCSSがついていたが、
オーバーレイがオフだとこのクラス名はつかないので対象セレクタを変更
■ After
---
* プルしたか？
* ビルドしたか？

[ Design Bug Fix ] Fix an issue where the CSS is not applied when the navigation is set to always display

---

assets/_scss/_navigation_additional-class.scss

オーバーレイ : モバイル / スタイル : アクティブボーダー
の設定の時に編集画面でアクティブボーダーのスタイルが当たらない
ただし、この変更は 1.27.1 以降の変更に起因するので、 readme などには記載しない
公開画面側のナビゲーションは ul.wp-block-navigation__container だが、
編集画面は div.wp-block-navigation__container なので、
ul に対してではなく .wp-block-navigation__container 指定に変更

[ nav ] active border class が編集画面でいろいろ効かない不具合を修正

---

assets/_scss/_pagenation.scss
readme.txt
style.css

X-T9 PaginationのNextボタンに余白がありませんので修正 #312 
を引き継いでいます
* Prev ボタンの右、Next ボタンの左に余白がないので追加しました
* ページネーションで Prev ボタンと数字の間、数字と Next ボタンの間に余白がなくくっついていたので、余白が空くようになったか確認お願いします
* 下記が気になってるのでご意見もらえますか
* コアのCSS が強いため SCSS の記述がおかしい(やっつけ感アリ)かもしれない、適切な書き方がありましたらご指摘ください
* 今回 0.5em の余白を追加したが、数字と数字の間は `<br>`で空いているため微妙に空き具合が異なる、よい方法あったらご指摘ください
---
* プルしたか？
* ビルドしたか？

PaginationのPrev、Nextボタンに余白を追加して調整

---

readme.txt
theme.json

theme.json の新しいバージョンへの移行
https://ja.wordpress.org/team/handbook/block-editor/reference-guides/theme-json-reference/theme-json-migrations/
theme.json Version 3 リファレンス (最新)
https://ja.wordpress.org/team/handbook/block-editor/reference-guides/theme-json-reference/theme-json-living/

[ Specification Change ] Update theme.json to V3 from V2

---

readme.txt
styles/bg-black.json
styles/red.json
styles/sweet.json

外観 > エディタで スタイル（修正後の状態）が出なくなった。
これは WordPress が パレットやタイポグラフィのセットが追加できるようになったので、従来のスタイル指定のjsonには色しか指定してなかったのでパレット扱いにされたのだと思われる。
個人的には実際パレットしか指定してないので既存でいいのだが、初心者本がスタイルでの表記になってるため問い合わせが多いらしいので、スタイル表示にするために実際はどうでもいいが font の情報を追加
■ Before
■ After

[ Specification Change ] Add styles setting in syles json

---

assets/_scss/_footer.scss
readme.txt

[ Specification Change / Bug fix ] Add z-index:9999 to footer.wp-block-template-part

---

assets/_scss/_common.scss
readme.txt

[ 不具合修正 ] スライダーアイテムブロックの中に画像ブロックを配置して中央揃えにしても中央にならない不具合を修正

---

assets/_scss/_navigation_additional-class.scss
readme.txt

https://make.wordpress.org/core/2025/03/25/miscellaneous-block-editor-changes-in-wordpress-6-8/
の Consistent Class Application for Navigation Block Menu Items
WordPress 6.8から、current-menu-ancestor クラスが <li> 要素ではなく、<a> 要素に適用されるようになったため、CSSを追加しました。
6.8が配信されしばらく経った後に`.current-menu-ancestor`の記述を削除するようコメントアウトで書いてあります。
お一人確認で大丈夫かと思いますが何かありましたら二人目に回してください。
1. WordPress 6.7でナビゲーションブロックを使用して親子関係のあるメニューを作成しフロントエンドに表示されるよう配置
2. フロントエンドで1のメニューを確認し、親ページにオンマウスし子ページをクリックして子ページ開く
3. 子ページを開いたときに、子ページの親であるメニュー名に下線が適用されていることを確認
4. WordPress6.8に切り替えた際も子ページの親であるメニュー名に下線が適用されていることを確認
上記と同じ確認を行ってください。
---
* プルしたか？
* ビルドしたか？

【確認待ち】[ その他 ][ 6.8対応 ] ナビゲーションブロックにおける current-menu-ancestor CSS クラス適用の修正

---

functions.php
readme.txt

The description display process was set to run on versions earlier than 6.8, but it was also running on 6.8 RC. Therefore, it has been modified so that it no longer runs on 6.8 RC.
■ Before

6.8 RC でナビゲーションディスクリプションが２重で表示される不具合を修正

---

readme.txt
templates/home.html

[ 不具合修正 ] ホームテンプレートの初期状態で文字が改行されてる＆右に寄っている不具合を修正

---

readme.txt
templates/home.html
templates/index.html
templates/search.html
theme.json

https://github.com/vektor-inc/x-t9/issues/347
loop-archive テンプレートパーツを編集しようとしてクエリを改変されると、検索結果ページなど他のページでも影響を受けてしまうため
テンプレートパーツ loop-archive として読み込んでいたものを非同期パターンに変更

[ Specification Change ] Abolished the loop-archive template

---

assets/_scss/_footer.scss
readme.txt

フッターの z-index をhttps://github.com/vektor-inc/x-t9/pull/364 で上げた事により、フッターに配置したモーダルメニューが固定ヘッダーの下になり、閉じるボタンが押せなくなってしまった。
モーダルが開いている時にフッターの z-index を上げる
* npm run build
* フッターのメニューにモバイルで開いて、ヘッダーに埋まらない事を確認
実装者に同じ
---
* プルしたか？
* ビルドしたか？

【確認待ち】[ 不具合修正 ] フッターに配置したメニューがモーダルになった時にヘッダーの下に埋まる不具合を修正

---

assets/_scss/_block_width.scss
readme.txt

[ 不具合修正 ] コンテンツ幅の投稿コンテンツ直下に幅広要素を配置した場合に、中央にならない不具合を修正

---

assets/_scss/_block_width.scss
readme.txt

■ Before
■ After
```
<div class="wp-block-group has-border-color has-vivid-purple-border-color" style="border-width:1px">
<div class="wp-block-group" style="border-right-color:var(--wp--preset--color--vivid-red);border-right-width:2px;border-left-color:var(--wp--preset--color--vivid-red);border-left-width:2px;padding-right:var(--wp--preset--spacing--40);padding-left:var(--wp--preset--spacing--40)">
<p>ヘッダー</p>
</div>
</div>
<div class="wp-block-group alignfull has-border-color has-vivid-purple-border-color" style="border-width:1px">
<div class="wp-block-group alignfull has-border-color has-vivid-green-cyan-border-color" style="border-width:1px">
<div class="wp-block-group" style="border-right-color:var(--wp--preset--color--vivid-red);border-right-width:2px;border-left-color:var(--wp--prese …
```

[ 不具合修正 ] Windows端末でブロックの入れ子の状態によってはレイアウトが崩れる不具合を修正

---

assets/_scss/_block_width.scss

https://github.com/vektor-inc/x-t9/pull/376#issuecomment-3100633762 で、全幅内に配置した幅広ブロックが左に寄ってしまったので、テンプレートの作りの問題かと思い、マージしましたが、改めてcssを見ていて、全幅内に配置した幅広にも以下のcssがついてしまうのはおかしいな(テンプレートの作りの問題ではない)と思いまして、alignfull／alignwide 内に置いた alignwide は中央になるようにコードを追加しました。
**▼ 全幅内に配置した幅広ブロックにも以下のcssがついてしまう**
```
.alignwide {
/* 既存コード */
.is-layout-constrained:where(:not(:is(.alignfull, .alignwide))) > :where(:not(:is(.alignfull, .alignwide))) & {
margin-left: calc((100% - var(--wp--custom--width--wrapper)) / 4) !important;
margin-right: calc((100% - var(--wp--custom--width--wrapper)) / 4) !important;
}
}	
```
1人は石川さんに確認していただきたいです。
alignfull／alignwide 内に置いた alignwide は中央寄せになるようにcssを調整しました。 …

alignfull／alignwide 内に置いた alignwide が 中央に配置されない問題を修正
