vektor-inc/x-t9

- .gitignore
- assets/_js/_master.js
- assets/_scss/_header.scss
- assets/_scss/editor.scss
- functions.php
- inc/patterns/header-logo-nav-float-contact-inline.php
- inc/patterns/header-logo-nav-float-contact-top.php
- inc/patterns/header-site-title-nav-float-contact-top.php
- package-lock.json
- package.json
- readme.txt
- webpack.js
https://github.com/vektor-inc/x-t9/issues/1
> [ 機能追加 ] スクロール時ヘッダー固定対応

- inc/block-patterns.php
- inc/patterns/header-logo-nav-center.php
- inc/patterns/header-logo-nav-contact-flex-between-wide.php
- inc/patterns/header-logo-nav-contact-side-by-side-wide.php
ヘッダーのパターンに、下記３つを追加しました。
1. ロゴ・キャッチフレーズ・ナビゲーションが中央揃えのレイアウト
2. 幅広かつナビゲーションがロゴ寄りの横並びのレイアウト
3. 幅広かつロゴ・ナビゲーション・ボタンが等間隔の横並びのレイアウト
なお、幅広は幅が中途半端な気がしたので、全幅にして左右に4vwのpaddingをいれて調整してます。
1のレイアウト
2のレイアウト
3のレイアウト
実装者が確認した手順を箇条書きで記載してください。
* 
*
*
（　どこかのデモサイトかテストサーバーにデプロイ済みなどで確認できる場合はそのURL　）
レビュワーがどういう手順で何を確認して欲しいかを記載してください。
*
*
*
---
レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。
* プルしたか？
* ビルドしたか？
* キャッシュをクリアして確認したか？
> 【確認待ち】３つののヘッダーパターンを追加

- readme.txt
- theme.json
> [ 6.1 ] Cope with settings.spacing.spacingSizes

- assets/_scss/_navigation_additional-class.scss
- inc/patterns/footer-bg-dark-3col.php
- inc/patterns/footer-bg-dark.php
- inc/patterns/footer-bg-secondary-3col.php
> [ Fix ] Footer bottom menu class

- assets/_scss/_block_additional-class.scss
- assets/_scss/_sidebar.scss
- gulpfile.js
- inc/block-styles.php
- inc/patterns/columns/columns-menu.php
- inc/patterns/featured/featured-columns-menu.php
- inc/patterns/featured/featured-post-list.php
- inc/patterns/footer/footer-bg-secondary-center-nav.php
- inc/patterns/footer/footer-bg-secondary.php
- parts/footer.html
- parts/page-header-page.html
- parts/page-header-single.html
- readme.md
- readme.txt
- templates/404.html
- templates/front-page.html
- templates/home.html
- templates/index.html
- templates/page-2col.html
- templates/page.html
- templates/single-1col.html
- templates/single.html
- theme.json
> 余白システムの仕様変更

- assets/_scss/style.scss
- readme.txt
- style.css
> [ Bug fix ] Fix custom HTML block iframe preview don't display on editor screen.

- assets/_scss/_block.scss
- readme.txt
> Cope with Dark bg color about image caption text color.

- assets/_scss/_button.scss
- assets/_scss/_variables.scss
- readme.txt
https://github.com/vektor-inc/x-t9/issues/106
> Button color tuning

- parts/page-header-page.html
- parts/page-header-single.html
- readme.txt
- style.css
ページヘッダーの中身を group で囲うように変更
文字が多い時や左揃え指定など追加したらはみ出すため
> [ Change version ] 1.10.0

- assets/_scss/_block.scss
- assets/_scss/editor.scss
- readme.txt
https://github.com/vektor-inc/x-t9/issues/140
* インラインコードのデザインを追加しました。
* 背景色が黒のとき、`data-rich-text-format-boundary`がtrueでフォーカスがあたると背景色が変わり読みづらくなるのであわせて調整しています。
```scss
/* Inline Code ------------------------------------------------- */
.wp-block-post-content {
:not(pre) > code {
display: inline-flex;
margin: 0 0.5em;
padding: 0.25em 0.5em;
align-items: center;
background-color: var(--wp--preset--color--bg-secondary);
border: 1px solid var(--wp--preset--color--border-normal);
border-radius: 2px;
color: var(--wp--preset--color--text-normal);
font-size: 0.9em;
line-height: 1;
:focus:not(pre) > code[data-rich-text-format-boundary] {
background-color: var(--wp--preset--color--border-normal);
}
}
}
```
> 【確認待ち】インラインコードのデザインを追加

- assets/_scss/_block.scss
- readme.txt
https://github.com/vektor-inc/x-t9/issues/147
以下のコードを貼り付けて vk_list_クラスあり無しでデザインに違いが出ない事を確認
```
<h2 class="wp-block-heading">vk_list_クラスありUL</h2>
<ul class="is-style-vk-frown-mark vk_block-margin-sm--margin-top my-additional-list-class has-cyan-bluish-gray-background-color has-background">
<li>リスト1</li>
<li>リスト2</li>
</ul>
<h2 class="wp-block-heading">vk_list_クラスありOL</h2>
<ol class="is-style-vk-frown-mark vk_block-margin-sm--margin-top my-additional-list-class has-cyan-bluish-gray-background-color has-background">
<li>リスト1</li>
<li>リスト2</li>
</ol>
<h2 class="wp-block-heading">vk_list_クラスなしUL</h2>
<ul class="is-style-vk-frown-mark vk_block-margin-sm--margin-top has-cyan-bluish-gray-background-color has-background">
<li>リスト1</li>
<li>リスト2</li>
</ul>
<h2 …
```
> [ Specification Change ] Change list style selector for side navigation

- readme.txt
- theme.json
Not using
https://make.wordpress.org/core/2022/10/03/fluid-font-sizes-in-wordpress-6-1/
> [ Specification Change ] Font size system ( not using core fluid system )

- assets/_scss/_common.scss
- readme.txt
https://github.com/vektor-inc/x-t9/issues/163
横スクロールが出ないようにCSS補正
スクロールバー表示状態で全幅コンテンツを配置して横するクロールが出ない事を確認
https://www.vektor-inc.co.jp/
またはローカル
スクロールバー表示状態で全幅コンテンツを配置して横するクロールが出ない事を確認
---
レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。
* プルしたか？
* ビルドしたか？
* キャッシュをクリアして確認したか？
> 【確認待ち】Cope with not intend horizontal scrollbar display #163

- assets/_scss/_block_width.scss
- assets/_scss/plugin-override/_vk-blocks-override.scss
- readme.txt
https://github.com/vektor-inc/x-t9/issues/171
幅処理のCSS調整
実装者が確認した手順を箇条書きで記載してください。
以下コードを貼り付けて公開画面と編集画面で確認幅広が左に寄ったりしないか確認
<details>
<summary>
該当のコード クリックで表示
</summary>
<div>
コード
```HTML
<h2 class="wp-block-heading">グループブロックでラップ(ブロック間隔を設定)</h2>
<div class="wp-block-group alignfull">
<div class="wp-block-group has-border-color has-primary-border-color" style="border-width:5px">
<p class="has-text-align-center">なし</p>
</div>
<div class="wp-block-group alignwide has-border-color has-primary-border-color" style="border-width:5px">
<p class="has-text-align-center">幅広</p>
</div>
<div class="wp-block-group alignfull has-border-color has-primary-border-color" style="border-width:5px">
<p class="has-text-align-center">全幅</p>
</div>
</div>
<h2 …
```
> 【確認待ち】[ Bug fix ] Fix content width control  #171

- assets/_scss/_common.scss
- readme.txt
1.14.0 - 1.15.0 でヘッダー固定が反応しなくなる不具合を修正
> [ Bug fix ] Fix Header fix not work since 1.14.0

- inc/patterns/footer/footer-bg-dark-3col.php
> フッターの不要なクラス指定削除 / delete unnecessary class on footer nav

- assets/_scss/plugin-override/_vk-blocks-override.scss
- readme.txt
> [ Design Tuning ][ VK Blocks icon ] Margin tuning of Icon Block of the VK Blocks

- inc/patterns/featured/featured-post-list.php
- readme.txt
[翻訳対応] Information list #209 
* トップページのボタンの語句「Information list」を翻訳可能にしました　→「お知らせな」タイトルに合わせて
* `inc/patterns/featured/featured-post-list.php` のなかでボタンの語句 `Information list` を翻訳可能な状態になっているか？
* `inc/patterns/featured/featured-post-list.php` のなかでボタンの語句 `Information list` を翻訳可能な状態になっているか？
* ここではコードのみ確認
* 実際には [GlotPress](https://translate.wordpress.org/locale/ja/default/wp-themes/x-t9/) に反映されてから翻訳して、表示を確認することができます
---
* プルしたか？
* ビルドしたか？
>  [翻訳対応] トップページのボタン「Information list」

- assets/_scss/_navigation.scss
- readme.txt
> Fixed a bug where the submenu's background color and text color were not being applied.

- assets/_scss/_header_additional-class.scss
- theme.json
サイトタイトルへのフォントサイズ指定をtheme.jsonに移行したい #228 
* サイトタイトルへのフォントサイズ指定をtheme.jsonに移行しました
* `theme.json` に書いた `core/site-title` の `fontSize` が反映される
* `theme.json` に書いた c`ore/site-title` の `fontSize` が反映される
* サイトタイトルタグへのデザイン指定をCSSファイルからtheme.jsonに移行 #226 と似ているため、readme 記載していません
---
* プルしたか？
* ビルドしたか？
> サイトタイトルへのフォントサイズ指定をtheme.jsonに移行

- assets/_scss/_block.scss
- readme.txt
日付を途中で改行するケースのほうがレアなため
CSSで nowrap 指定追加
> [ Specification Change ] Add nowrap CSS specification to post date block.

- assets/_scss/_sidebar.scss
- readme.txt
以下のような、個別投稿のサイドバーのh4のデザインをスタイルから選択しても背景のグレーが残る現象に対応しました。
1. [サイトエディター] > [テンプレート] > [個別投稿] に移動
2. サイドバーのh4を選択し、スタイルから適当なものを選び更新(画像は[二重線 上下線 黒])
3. フロントエンドで「二重線 上下線 黒」のデザインが適用されました。
今回の変更は、以下の.is-style-main-layout-sidebar select にも影響がある変更です。
```
.is-style-main-layout-sidebar select {
width: 100%;
}
```
そのため、サイドバーでセレクトボックスを使う場合にも影響がないことを確認しています。
確認方法としては、以下のようにカテゴリーなどを[ドロップダウンで表示]にした後、
横幅が100%になっていることを確認しています。
1. [サイトエディター] > [テンプレート] > [個別投稿] に移動します。
2. サイドバーのh4を選択し、スタイルから適当なものを選び更新(画像は[二重線 上下線 黒])
3. フロントエンドで「二重線 上下線 黒」のデザインが適用されました。
4. カテゴリーブロックなどを[ドロップダウンで表示]に設定&更新し、横幅が100%になっているかを確認してください。
---
* プルしたか？
* ビルドしたか？
* composer …
> 【フロントエンドのみ】個別投稿でサイドバーのh4のデザインを変えられない現象を対応

- assets/_scss/_common_margin-vertical.scss
- readme.txt
https://github.com/vektor-inc/x-t9/issues/247
li の直下にul がきた場合は除外するような擬似クラスを追加しました。
cssの微修正のため、1人確認で良いかもしれません。
リストブロックを配置します。
適当にテキスト項目を6つくらい入れて、適当にいくつかインデントさせます。
インデントされた`<li>`の中の`<ul>`タグにmarginがついていないことを確認してください。
---
* プルしたか？
* ビルドしたか？
> [ css ] fix:インデントしているulにはmarginがつかないように

- readme.txt
- theme.json
背景 にサイズ指定を追加
---
* プルしたか？
* ビルドしたか？
> [ Specification Change ][ 6.5 ] Attend to backgroundSize

- readme.txt
- theme.json
> [ 6.5 ] Attend to aspectRatio

- gulpfile.js
- package.json
- readme.txt
- templates/404.html
- templates/home.html
- templates/index.html
- templates/page-2col.html
- templates/page.html
- templates/search.html
- templates/single-1col.html
- templates/single.html
https://github.com/vektor-inc/x-t9/issues/264
* "theme":"x-t9" 削除
* build 時に "theme":"x-t9", を自動的に削除するスクリプトを追加
> [ Specification Change ] Delete theme name from templates.

- inc/patterns/footer/footer-bg-dark-3col.php
- inc/patterns/footer/footer-bg-dark.php
- inc/patterns/footer/footer-bg-secondary-3col.php
- inc/patterns/footer/footer-bg-secondary-center-nav.php
- inc/patterns/footer/footer-bg-secondary.php
- inc/patterns/header/desc--sns__logo--nav-contact.php
- inc/patterns/header/logo-title--sns-contact__nav.php
- readme.txt
パターンなどに使用していた twitter アイコンを X アイコンに変更
> Change the twitter icon to X

- inc/patterns/header/desc--sns__logo--nav-contact.php
- readme.txt
> [ Design Bug fix ] Fix Description -- SNS / Logo -- Nav - Contact pattern alignment

- assets/_scss/_block_styles.scss
- readme.txt
- theme.json
VK Blocks Proの [#1987](https://github.com/vektor-inc/vk-blocks-pro/issues/1987)
にあるように、XXSとXXLのレスポンシブスペーサーが追加されるため、テーマ側で設定されているスペーサースタイルにXXLを追加しました。
1. 編集画面でコアのスペーサーを追加
2. コアのスペーサーのスタイルから「XXL」を選択
3. 編集画面、フロントエンドでis-style-spacer-xxlや、spacingが9remになっているかを確認
1. 編集画面でコアのスペーサーを追加してください。
2. コアのスペーサーのスタイルから「XXL」を選択してください。
3. 編集画面、フロントエンドでis-style-spacer-xxlや、spacingが9remになっているかを確認してください。
---
* プルしたか？
* ビルドしたか？
> スペーサーのスタイルでXXLを追加

- inc/block-styles.php
- readme.txt
- style.css
https://github.com/vektor-inc/x-t9/pull/272
UI実装漏れ
> [ Change version ] 1.24.1 / Add spacer block style XXL

- assets/_scss/_navigation.scss
- readme.txt
#218 
ナビゲーションブロックで、レイアウトの方向を「縦並び」かつ「中央・右揃え」が効かない現象に対応しました。
※ その他のナビゲーションの修正は #245 をご確認ください。
---
* プルしたか？
* ビルドしたか？
> [ナビゲーション] レイアウトの方向を「縦並び」かつ「中央・右揃え」が効かない現象に対応

- assets/_scss/_block.scss
- readme.txt
https://github.com/vektor-inc/lightning/issues/633
(このプルリクがマージされた後、他のテーマにも適用していきます。)
インラインの「キーボード入力」でスタイルを追加しました。
編集画面のツールバーから「キーボード入力」を設定し、フロントエンドでスタイルを確認しました。
編集画面のツールバーから「キーボード入力」を設定し、フロントエンドでスタイルを確認してください。
---
* プルしたか？
* ビルドしたか？
> エディターで キーボード入力 のスタイル追加

- assets/_scss/editor.scss
- package-lock.json
- readme.txt
WordPress 6.6 で固定ヘッダーが編集画面でめりこんでしまう
編集画面でヘッダー固定の解除
> Fix scrolled header for WP6.6

- assets/_scss/_button.scss
- readme.txt
https://github.com/vektor-inc/x-t9/issues/214
パターンをチェックしていて気になるため、以下修正しました。
VKボタンのボタンスタイル「ベタ塗り」の背景色：白色、文字の色をカスタムカラーにした場合、hover時の文字色がフロント画面で白になるので、文字色が指定されている場合は:notで除外しました。
コアのボタンのボタンスタイル「輪郭」で、テキストの色指定がある場合、hover時の文字色が白になりますが、例えば背景に白っぽい色を設定している場合にも白になってしまいテキストの色が見えづらくなるため、背景色がある場合は:notで除外しました。
cssのため書いていません。
固定ページなどに、コードエディタにして以下のコードを貼ってください。
VK ボタンのスタイル「塗りつぶし」の背景が白で文字色がカスタムカラーのボタンをhoverして、文字色が白にならないことを確認してください。
コアのボタンブロックのスタイル「輪郭」でテキスト色と背景色が指定してあるボタンをhoverして、文字色が白にならないことを確認してください。
```
<div class="wp-block-group alignfull has-background" style="background-color:#00000091;padding-top:var(--wp--preset--spacing--70);padding-right:0;padding-bottom:var(--wp--preset--s …
```
> 【２人目確認待ち】css微修正:vkボタン塗りのhover時とコアOutlineのhover時の白文字が一部除外指定でつかないように調整

- assets/_scss/_button.scss
- readme.txt
https://discord.com/channels/1010092469863587892/1010175825930367019/1286250345361707120
パターンライブラリにあるコアのボタン(スタイル「輪郭」)ブロックをX-T9にコピペすると、has-vk-color-primary-colorを使ってプライマリーカラーを設定してある部分が、反映されませんでしたのでその部分を修正しました。
→ CSSを追加しただけなので書いてません。
https://patterns.vektor-inc.co.jp/vk-patterns/18730/ を編集画面にコピペし、一番最初のボタンブロックにて以下の色が反映されていることを確認しました。
```
:root .has-vk-color-primary-color, :root .editor-styles-wrapper .has-vk-color-primary-color {
color: var(--wp--preset--color--vk-color-primary);
}
```
また、以下のいろいろなボタンブロックのパターンをコピペしてもこのプルリクによる悪影響がないことを確認しました。
```
<div class="wp-block-group alignfull has-background" style="background-color:#00000091;padding-top:var(--wp--preset--spacing--70);padding-right:0;p …
```
> 【2人目確認中】[ core/button ] スタイル「輪郭」に設定してあるhas-vk-color-primary-colorの色が反映されないのを修正しました

- inc/block-styles.php
- readme.txt
以下のエラーの回避
一連の register_block_style を after_setup_theme で呼び出すように変更
テストは不要と判断
- [] ブロックスタイルが正常に表示されること
---
* プルしたか？
* ビルドしたか？
> WP6.7での翻訳エラー回避

- readme.txt
- theme.json
https://github.com/vektor-inc/vk-patterns/issues/371#issuecomment-2487176292
WP6.7から追加されたタイポグラフィの「方向」オプションをテーマでサポートしました。
これにより、縦書きが簡単にできるようになります。
@kurudrive 問題ないかと思いますがもし何かありましたらお書きください。
→theme.jsonにサポートを追加しただけなのでスキップ。
WP6.7でタイポグラフィのオプションに「方向」が追加されていることを確認しました。
また、縦書きを選択した時に縦書きが機能していることを確認しました。
実装者と同じ確認を行ってください。
---
レビューしてみて意図した動作をしない場合は再度ビルドするなど以下の項目を確認してください。
* プルしたか？
* ビルドしたか？
* キャッシュをクリアして確認したか？
> [ WP6.7 ] タイポグラフィの「方向」オプションをサポートしました

- assets/_scss/_pagenation.scss
issuesのリンク
https://github.com/vektor-inc/x-t9/issues/312
変更ファイル
assets/_scss/_pagenation.scss
変更箇所
margin-right:0.5em; を追加
---
* プルしたか？
* ビルドしたか？
>  X-T9 の Pagination 修正・Nextボタン要素の左側の余白を調整

- assets/_scss/_navigation.scss
- assets/_scss/_navigation_additional-class.scss
https://github.com/vektor-inc/x-t9/issues/315
https://github.com/vektor-inc/x-t9/pull/314 の変更が原因で以下のようになってしまった...
■ 変更前
セレクタの修正
■ 変更後
-> リリース前の変更に起因する不具合なので記載しない
---
* プルしたか？
* ビルドしたか？
> ナビゲーションでPC用のスタイル指定がオーバーレイメニューで効いてしまう不具合を修正

- assets/_scss/_navigation_additional-class.scss
↓の変更で効かなくなってしまっていた
https://github.com/vektor-inc/x-t9/pull/316/files
メニューが存在しないサイトの場合、ナビゲーションブロックの ul のクラスは .wp-block-navigation__container ではなく .wp-block-page-list であるが、.wp-block-page-list 指定がなかったために nav--active-border-bottom クラスのデザイン指定が反映されない不具合を修正
.wp-block-navigation__container 指定を :where( .wp-block-navigation__container, .wp-block-page-list ) 指定に変更
→ リリース前の変更が原因のため記載しない
---
* プルしたか？
* ビルドしたか？
> 新規サイトのときにアクティブボーダークラスが当たらない不具合を修正

- assets/_scss/_block_width_editor.scss
- readme.txt
全幅にしても左右に余白が空いてしまう...
■ After
```
<h2 class="wp-block-heading">グループブロックでラップ(ブロック間隔を設定)</h2>
<div class="wp-block-group alignfull">
<div class="wp-block-group has-border-color has-primary-border-color" style="border-width:5px">
<p class="has-text-align-center">なし</p>
</div>
<div class="wp-block-group alignwide has-border-color has-primary-border-color" style="border-width:5px">
<p class="has-text-align-center">幅広</p>
</div>
<div class="wp-block-group alignfull has-border-color has-primary-border-color" style="border-width:5px">
<p class="has-text-align-center">全幅</p>
</div>
</div>
<h2 class="wp-block-heading">何もラップしていない</h2>
<div class="wp-block-group has-border-color has-primary-border-color" style="border-width:5px">
<p …
```
> 【編集画面】幅処理不具合修正 / Fixed an issue with full-width processing in the editor.

- assets/_scss/plugin-override/_vk-blocks-override.scss
- readme.txt
https://github.com/vektor-inc/vk-blocks-pro/issues/1689
[[ アイコン ] 下部に余白ができてしまうのを修正しました](https://github.com/vektor-inc/vk-blocks-pro/pull/2430) がマージされたので、X-T9で補正用に書かれていたCSSを削除しました。
確認する方は1人でOKです。
1. VK Blocks Proのdevelopを最新の状態にfetchし、`npm run build`
2. 固定ページでアイコンブロックを配置
3. フロントエンドでアイコンブロックの下部に余白ができないことを確認。
4. フロントエンドで検証モードを行い、`vk_icon_frame`を選択した際、`.vk_icon_frame`のstyle.cssが複数当たっていないことを確認。
実装者と同じ内容を確認してください。
---
* プルしたか？
* ビルドしたか？
> [ Specification Change / Design Tuning ][ VK Blocks icon ] VK Blocks の Icon ブロックのマージン調整を削除

- assets/_scss/_common.scss
- readme.txt
https://vws.vektor-inc.co.jp/forums/topic/%e3%82%a2%e3%83%83%e3%83%97%e3%83%abos%e4%bb%a5%e5%a4%96%e3%81%aechrome%e3%81%ab%e3%81%8a%e3%81%91%e3%82%8b%e3%82%bf%e3%83%83%e3%83%81%e3%83%87%e3%83%90%e3%82%a4%e3%82%b9%e3%81%ae%e3%82%b9%e3%83%a0
iOSではなく、Androidなどの実機で症状が確認できるため、私の記憶で、実機をもっていそうな方をレビュワーとさせていただきましたが、もし他の方で確認できそうな方がいらっしゃいましたらご確認いただけると嬉しいです
元々、bodyには横スクロールが発生するのを防ぐために `overflow-x: hidden;` が指定されていますが、これによりナビゲーションモーダルメニューオープン時、同一ページ内リンク（アンカーリンク）へのジャンプが正しく動作しない問題が発生するようでした。
そのため、モーダルメニューが開いている間のみ `overflow-x: visible; `に上書きするCSSを追加し、ページ内リンクが正常に機能するように対応しました。
<s>ExUnitの有効化設定で「スムーススクロール」はオフにしないとうまく動作しませんので、このプルリクはX-T9のテーマ側での微修正となります。</s> 
【追記メモ】
ExUnitの「スムーススクロール」はオンになっていても、「メイン設定」の「スムーススクロールタイプ」を「JavaScript」にしているとページ内リンクがスムーススクロールしないようでした。 …
> 【確認待ち】[ その他 ] ナビゲーションモーダルメニューが開いている時、bodyのoverflow-xを調整し、同一ページ内のページアンカーリンクが遷移するよう修正

- assets/_scss/_common_margin-vertical.scss
- readme.txt
ページ内リンクでヘッダーに要素が隠れてしまう
ページ内リンクは id 指定なので、id に対して scroll-margin-top を指定
■ Before
■ After
---
* プルしたか？
* ビルドしたか？
> [ 不具合修正 ] ページ内リンクのスムーススクロールでヘッダーの高さ分スクロール位置を調整するためのマージンを追加

- assets/_scss/_common_margin-vertical.scss
- readme.txt
アンカーリンク 固定ヘッダー用のCSSを調整
* 詳細度を下げる & forcus 対応追加
https://x.com/tak_dcxi/status/1921915328293962131
> [ Other ] アンカーリンク 固定ヘッダー用のCSSを調整

- inc/patterns/footer/footer-bg-dark-3col.php
- inc/patterns/footer/footer-bg-dark.php
- inc/patterns/footer/footer-bg-secondary-3col.php
- inc/patterns/footer/footer-bg-secondary-center-nav.php
- inc/patterns/footer/footer-bg-secondary.php
- inc/patterns/header/desc--sns__logo--nav-contact.php
- inc/patterns/header/logo-title--sns-contact__nav.php
- readme.txt
https://github.com/issues/assigned?issue=vektor-inc%7Cx-t9%7C342
ヘッダーやフッターのパターンの中にあるソーシャルアイコンブロックがデフォルトで「新しいタブでリンクを開く」がONになっているようにしました。
→パス
このブランチで、ソーシャルアイコンブロックが含まれるヘッダーのパターン(2種類)、フッターのパターン(5種類)をそれぞれ設置し、新しいタブでリンクを開くがONになっているか確認しました。
ONになってない場合、外観>エディタ>パターン>各パターン　からリセットするとONになるのではないかとおもいます。
同上
---
* プルしたか？
* ビルドしたか？
> [ 仕様変更 ][ SNSアイコン ] ヘッダーとフッターのブロックパターン内のSNSリンクを、デフォルトで別のタブで開くように変更

- assets/_scss/_button.scss
- readme.txt
> [ 仕様変更 ][ 検索ボタン ] 改行禁止指定追加 & 余白調整

- inc/patterns/header/logo-title--sns-contact__nav.php
- readme.txt
> [ 不具合修正 ][ ヘッダーパターン ] Logo - Site title -- ( SNS - Contact ) / Nav のモバイルトグルボタンの上部に余白がない不具合を修正

- assets/_scss/_common.scss
- readme.txt
> [ Revert ][ Typography ] Add text-box: trim-both text;

- readme.txt
- styles/bg-black.json
- styles/colors/01-bg-black.json
- styles/colors/02-red.json
- styles/colors/03-sweet.json
- styles/colors/04-foresty.json
- theme.json
> 追加カラー名を Secondary から Complementary に変更

- readme.txt
- theme.json
* Huge のサイズが小さすぎてもう少し大きい文字を使おうとすると手入力になる
* モバイルでの最小文字サイズの計算式が不規則だったので再調整
* X Huge / XX Huge / XXX Huge 追加
* 最小文字サイズを 最大文字サイズの0.875掛けに変更
---
* プルしたか？
* ビルドしたか？
> [ 仕様変更 ] XXX Huge / XX Huge / X Huge サイズ追加 / 最小サイズ変更

- assets/_scss/_block_width.scss
X-T9 の幅処理の SCSS についてマイナスオフセットの処理部分だけ分離
※ このプルリクでは挙動などの変更はナシ
> CSSファイルの構造変更（挙動に変化なし）
